version: 2.1

jobs:
  build:
    docker:
      - image: node:12 # You can use a different Node.js version as needed

    working_directory: ~/app

    steps:
      - checkout

      # Install dependencies
      - run:
          name: Install Dependencies
          command: npm install
          
      # Build
      - run:
          name: Build
          command: npm run build

      # Copy build artifacts to ~/ directory
      - run:
          name: Copy Build Artifacts
          command: cp -r ./build ~/ 

workflows:
  version: 2
  build:
    jobs:
      - build
