version: 2.1

jobs:
  build:
    docker:
      - image: node:12 # You can use a different Node.js version as needed

    working_directory: ~/app

    steps:
      - checkout

      # Install dependencies
      - run:
          name: Install Dependencies
          command: npm install

workflows:
  version: 2
  build:
    jobs:
      - build
