version: 2.1

jobs:
  build:
    docker:
      - image: cimg/base:stable

    steps:
      - checkout

      # Use setup_remote_docker to set up the Docker environment
      - setup_remote_docker

      # Install dependencies (if needed)
      - run:
          name: Install Dependencies
          command: echo "Install your dependencies here, if needed"

      # Build Docker image
      - run:
          name: Build Docker Image
          command: |
            sudo docker build -t test .

      # Run Docker container
      - run:
          name: Docker run
          command: |
            sudo docker run -d --network host test:latest

workflows:
  version: 2
  build:
    jobs:
      - build
      - Docker run
