version: 2.1

jobs:
  build:
    docker:
      - image: cimg/base:stable

    steps:
      - setup_remote_docker
      - checkout

      # Install dependencies
      - run:
          name: Install Dependencies
          command: npm install

      # Build Docker image
      - run:
          name: Build Docker Image
          command: |
            docker build -t test .

      # Run Docker container
      - run:
          name: Docker run
          command: |
            docker run -d --network host test:latest

workflows:
  version: 2
  build:
    jobs:
      - build
