version: 2.1
orbs:
  node: circleci/node@5.0.2

jobs:
  build_and_serve:
    docker:
      - image: cimg/base:2020.01
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run:
          command: npm i
          name: installing Deps
      - run:
          command: npm run build
          name: Build app
      - run:
          name: Serve build with Nginx
          command: |
            sudo apt-get update && sudo apt-get install -y nginx
            sudo cp -r ~/project/dist/* /var/www/html/
            sudo service nginx start

workflows:
  test_my_app:
    jobs:
      - build_and_serve
