version: 2.1

jobs:
  build:
    docker:
      - image: node:12 # You can use a different Node.js version as needed

    working_directory: ~/app

    steps:
      - checkout

      # Install dependencies
      - run:
          name: Install Dependencies
          command: npm install

      # Build Docker image
      - run:
          name: Build Docker Image
          command: |
            docker build -t test . 
      - run:
          name: Docker run
          command: |
            docker run -d --network host test:latest
          
workflows:
  version: 2
  build:
    jobs:
      - build
