version: 2.1
orbs:
  node: circleci/node@5.0.2

jobs:
  build_and_serve:
    docker:
      - image: cimg/base:2020.01
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - restore_cache:
          keys:
            - node-v1-{{ checksum "package-lock.json" }}
            # Add other cache keys as needed
      - run:
          name: Install Dependencies
          command: npm install
      - save_cache:
          paths:
            - ./node_modules
          key: node-v1-{{ checksum "package-lock.json" }}
            # Add other cache keys as needed
      - run:
          command: npm run build
          name: Build app
      - run:
          name: Serve build with Nginx
          command: |
            sudo apt-get update && sudo apt-get install -y nginx
            sudo cp -r ~/project/dist/* /var/www/html/
            sudo service nginx start

workflows:
  version: 2
  test_my_app:
    jobs:
      - build_and_serve
